const watches = [
  {
    id: 1,
    brand: "Tissot",
    name: "PRX Powermatic 80",
    movement: "Automatic",
    case_size: "40mm",
    price: 850,
    image: "/images/prx.png",
  },
  {
    id: 2,
    brand: "Mido",
    name: "Multifort Patrimony",
    movement: "Automatic",
    case_size: "40mm",
    price: 930,
    image: "/images/mido.png",
  },
  {
    id: 3,
    brand: "Longines",
    name: "PrimaLuna Moonphase",
    movement: "Self-winding mechanical",
    case_size: "41mm",
    price: 2800,
    image: "/images/longines.png",
  },
  {
    id: 4,
    brand: "Vacheron Constantin",
    name: "Historiques American 1921",
    movement: "Automatic",
    case_size: "40mm",
    price: 42000,
    image: "/images/vacheron-american-1.png",
  },
  {
    id: 5,
    brand: "Bulgari",
    name: "Octo Roma WorldTimer",
    movement: "Automatic",
    case_size: "45mm",
    price: 10000,
    image: "/images/bulgari.png",
  },
  {
    id: 6,
    brand: "Nomos Glashütte",
    name: "Club Sport Neomatik Worldtimer Trace",
    movement: "Automatic",
    case_size: "40mm",
    price: 5000,
    image: "/images/nomos.png",
  },
  {
    id: 7,
    brand: "Vacheron Constantin",
    name: "Malte Moon phase",
    movement: "Automatic",
    case_size: "42mm",
    price: 42000,
    image: "/images/vacheron-moon.png",
  },
  {
    id: 8,
    brand: "Baume & Mercier",
    name: "Clifton 10758 Moonphase",
    movement: "Automatic",
    case_size: "39mm",
    price: 4700,
    image: "/images/baume-clifton.png",
  },
  {
    id: 9,
    brand: "Longines",
    name: "Avigation Bigeye",
    movement: "Automatic",
    case_size: "41mm",
    price: 3800,
    image: "/images/longines-avigation.png",
  },
  {
    id: 10,
    brand: "Certina",
    name: "DS Super PH1000M STC",
    movement: "Automatic",
    case_size: "43.5mm",
    price: 1000,
    image: "/images/certina.png",
  },
  {
    id: 11,
    brand: "Omega",
    name: "Seamaster Aqua Terra",
    movement: "Automatic",
    case_size: "38mm",
    price: 7500,
    image: "/images/omega-seamaster.png",
  },
  {
    id: 12,
    brand: "Grand Seiko",
    name: "SLGB001 Evolution 9",
    movement: "Automatic",
    case_size: "37mm",
    price: 35000,
    image: "/images/grand-seiko.png",
  },
  {
    id: 13,
    brand: "Grand Seiko",
    name: "SBGJ277 Snow Valley",
    movement: "Automatic",
    case_size: "44.2mm",
    price: 7500,
    image: "/images/grand-seiko-snow.png",
  },
  {
    id: 14,
    brand: "Zenith",
    name: "G.F.J. Exclusive Edition",
    movement: "Manual",
    case_size: "39.15mm",
    price: 45000,
    image: "/images/zenith-g-f-j.png",
  },
  {
    id: 15,
    brand: "Zenith",
    name: "Chronomaster Original Triple Calendar",
    movement: "Automatic",
    case_size: "38mm",
    price: 13000,
    image: "/images/zenith-chronomaster.png",
  },
  {
    id: 16,
    brand: "Oris",
    name: "Big Crown Cervo Volante",
    movement: "Automatic",
    case_size: "40mm",
    price: 2600,
    image: "/images/oris.png",
  },
  {
    id: 17,
    brand: "Formex",
    name: "Essence Ceramica",
    movement: "Automatic",
    case_size: "41mm",
    price: 3700,
    image: "/images/formex.png",
  },
  {
    id: 18,
    brand: "Glashütte Original",
    name: "PanoMaticLunar",
    movement: "Automatic",
    case_size: "40mm",
    price: 12000,
    image: "/images/pano_matic_lunar.png",
  },
  {
    id: 19,
    brand: "Laurent Ferrier",
    name: "Classic Moon",
    movement: "Automatic",
    case_size: "40mm",
    price: 87000,
    image: "/images/classic_moon.png",
  },
];

export function fetchWatches() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(watches);
    }, 1000);
  });
}
